<div class="container">
    <div id="input">
        <h2>Input code</h2>
        <textarea name="textarea-input" id="textarea-input"></textarea>
    </div>
    <button id="convert-btn">Convert code</button>

    <div id="output">
        <h2>Output code</h2>
        <div id="code-container">
            <pre id="textarea-output"></pre>
        </div>
    </div>

</div>

<script type="module" src="./assets/JS/main.js"></script>