<div class="container">
    <div id="input">
        <form method="post" id="dnt-form">
            <textarea name="textarea-input" id="textarea-input"></textarea>
            <input type="submit" value="Convert code">
        </form>
    </div>

    <div id="output">
        <textarea name="textarea-output" id="textarea-output"></textarea>
    </div>

</div>

<script type="module" src="./assets/JS/main.js"></script>