<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WebApp To C++ Back-End</title>
    <link rel="stylesheet" href="assets/style/main.css">
</head>

<body>
    <header>
        <h1>webapp_to_esp32_server</h1>
    </header>
    <main>
        <?php require_once $template; ?>
    </main>
</body>

</html>