<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wrap_WebApp_Into_client.println("");</title>
    <link rel="stylesheet" href="assets/style/main.css">
</head>

<body>
    <header>
        <h1>Wrap_WebApp_Into_client.println("");</h1>
    </header>
    <main>
        <?php require_once $template; ?>
    </main>
    <footer>
        <a href="https://thomastestaud.com/" target=”_blank”>Made by Thomas</a>
    </footer>
</body>

</html>